language: julia

os:
    - linux

notifications:
    email: false

script:
  - julia -e 'Pkg.init(); run(`ln -s $(pwd()) $(Pkg.dir("Claw"))`); Pkg.pin("Claw"); Pkg.resolve()'
  - julia -e 'using Claw; @assert isdefined(:Claw); @assert typeof(Claw) === Module'
